package com.dpcl2.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.1
 * 2019-03-30T15:10:48.115+08:00
 * Generated source version: 3.3.1
 *
 */
@WebService(targetNamespace = "urn:dpcl:wsdl:2011-09-02", name = "DPCL2PortType")
@XmlSeeAlso({ObjectFactory.class})
public interface DPCL2PortType {

    /**
     * Add actions to a job.
     */
    @WebMethod(operationName = "SubmitAction")
    @RequestWrapper(localName = "SubmitAction", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "com.dpcl2.ws.client.SubmitAction")
    @ResponseWrapper(localName = "SubmitActionResponse", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "com.dpcl2.ws.client.SubmitActionResponse")
    @WebResult(name = "output", targetNamespace = "")
    public com.dpcl2.ws.client.SubmitActionOutput submitAction(
        @WebParam(name = "SubmitActionInput", targetNamespace = "")
        com.dpcl2.ws.client.SubmitActionInput submitActionInput
    );

    /**
     * Exchange a message with a tunnel.
     */
    @WebMethod(operationName = "ExchangeMessage")
    @RequestWrapper(localName = "ExchangeMessage", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "com.dpcl2.ws.client.ExchangeMessage")
    @ResponseWrapper(localName = "ExchangeMessageResponse", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "com.dpcl2.ws.client.ExchangeMessageResponse")
    @WebResult(name = "output", targetNamespace = "")
    public com.dpcl2.ws.client.ExchangeMessageOutput exchangeMessage(
        @WebParam(name = "ExchangeMessageInput", targetNamespace = "")
        com.dpcl2.ws.client.ExchangeMessageInput exchangeMessageInput
    );

    @WebMethod(operationName = "StartJob")
    @RequestWrapper(localName = "StartJob", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "com.dpcl2.ws.client.StartJob")
    @ResponseWrapper(localName = "StartJobResponse", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "com.dpcl2.ws.client.StartJobResponse")
    @WebResult(name = "output", targetNamespace = "")
    public com.dpcl2.ws.client.StartJobOutput startJob(
        @WebParam(name = "StartJobInput", targetNamespace = "")
        com.dpcl2.ws.client.StartJobInput startJobInput
    );

    /**
     * Change the power state of the printer.
     */
    @WebMethod(operationName = "SetPowerState")
    @RequestWrapper(localName = "SetPowerState", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "com.dpcl2.ws.client.SetPowerState")
    @ResponseWrapper(localName = "SetPowerStateResponse", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "com.dpcl2.ws.client.SetPowerStateResponse")
    @WebResult(name = "output", targetNamespace = "")
    public com.dpcl2.ws.client.SetPowerStateOutput setPowerState(
        @WebParam(name = "SetPowerStateInput", targetNamespace = "")
        com.dpcl2.ws.client.SetPowerStateInput setPowerStateInput
    );

    /**
     * Attempt to force-complete a job.
     */
    @WebMethod(operationName = "RestartJob")
    @RequestWrapper(localName = "RestartJob", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "com.dpcl2.ws.client.RestartJob")
    @ResponseWrapper(localName = "RestartJobResponse", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "com.dpcl2.ws.client.RestartJobResponse")
    @WebResult(name = "output", targetNamespace = "")
    public com.dpcl2.ws.client.RestartJobOutput restartJob(
        @WebParam(name = "RestartJobInput", targetNamespace = "")
        com.dpcl2.ws.client.RestartJobInput restartJobInput
    );

    /**
     * Service definition of function DPCL2__RetrieveInfo
     */
    @WebMethod(operationName = "RetrieveInfo")
    @RequestWrapper(localName = "RetrieveInfo", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "com.dpcl2.ws.client.RetrieveInfo")
    @ResponseWrapper(localName = "RetrieveInfoResponse", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "com.dpcl2.ws.client.RetrieveInfoResponse")
    @WebResult(name = "output", targetNamespace = "")
    public com.dpcl2.ws.client.RetrieveInfoOutput retrieveInfo(
        @WebParam(name = "RetrieveInfoInput", targetNamespace = "")
        com.dpcl2.ws.client.RetrieveInfoInput retrieveInfoInput
    );

    /**
     * Discover static information about the printer. Deprecates .
     */
    @WebMethod(operationName = "DiscoverPrinter2")
    @RequestWrapper(localName = "DiscoverPrinter2", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "com.dpcl2.ws.client.DiscoverPrinter2")
    @ResponseWrapper(localName = "DiscoverPrinter2Response", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "com.dpcl2.ws.client.DiscoverPrinter2Response")
    @WebResult(name = "output", targetNamespace = "")
    public com.dpcl2.ws.client.DiscoverPrinter2Output discoverPrinter2(
        @WebParam(name = "DiscoverPrinter2Input", targetNamespace = "")
        com.dpcl2.ws.client.DiscoverPrinter2Input discoverPrinter2Input
    );

    /**
     * Submit data to an action.
     */
    @WebMethod(operationName = "SubmitData")
    @RequestWrapper(localName = "SubmitData", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "com.dpcl2.ws.client.SubmitData")
    @ResponseWrapper(localName = "SubmitDataResponse", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "com.dpcl2.ws.client.SubmitDataResponse")
    @WebResult(name = "output", targetNamespace = "")
    public com.dpcl2.ws.client.SubmitDataOutput submitData(
        @WebParam(name = "SubmitDataInput", targetNamespace = "")
        com.dpcl2.ws.client.SubmitDataInput submitDataInput
    );

    /**
     * Reusume a previously Exchanged message that timed out.
     */
    @WebMethod(operationName = "ResumeMessage")
    @RequestWrapper(localName = "ResumeMessage", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "com.dpcl2.ws.client.ResumeMessage")
    @ResponseWrapper(localName = "ResumeMessageResponse", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "com.dpcl2.ws.client.ResumeMessageResponse")
    @WebResult(name = "output", targetNamespace = "")
    public com.dpcl2.ws.client.ResumeMessageOutput resumeMessage(
        @WebParam(name = "ResumeMessageInput", targetNamespace = "")
        com.dpcl2.ws.client.ResumeMessageInput resumeMessageInput
    );

    @WebMethod(operationName = "WaitForStatus2")
    @RequestWrapper(localName = "WaitForStatus2", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "com.dpcl2.ws.client.WaitForStatus2")
    @ResponseWrapper(localName = "WaitForStatus2Response", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "com.dpcl2.ws.client.WaitForStatus2Response")
    @WebResult(name = "output", targetNamespace = "")
    public com.dpcl2.ws.client.WaitForStatus2Output waitForStatus2(
        @WebParam(name = "WaitForStatus2Input", targetNamespace = "")
        com.dpcl2.ws.client.WaitForStatus2Input waitForStatus2Input
    );

    /**
     * Discover static information about the printer.
     */
    @WebMethod(operationName = "DiscoverPrinter")
    @RequestWrapper(localName = "DiscoverPrinter", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "com.dpcl2.ws.client.DiscoverPrinter")
    @ResponseWrapper(localName = "DiscoverPrinterResponse", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "com.dpcl2.ws.client.DiscoverPrinterResponse")
    @WebResult(name = "output", targetNamespace = "")
    public com.dpcl2.ws.client.DiscoverPrinterOutput discoverPrinter(
        @WebParam(name = "DiscoverPrinterInput", targetNamespace = "")
        com.dpcl2.ws.client.DiscoverPrinterInput discoverPrinterInput
    );

    /**
     * Get status on printer, supplies and jobs with adjustable triggers.
     */
    @WebMethod(operationName = "WaitForStatus")
    @RequestWrapper(localName = "WaitForStatus", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "com.dpcl2.ws.client.WaitForStatus")
    @ResponseWrapper(localName = "WaitForStatusResponse", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "com.dpcl2.ws.client.WaitForStatusResponse")
    @WebResult(name = "output", targetNamespace = "")
    public com.dpcl2.ws.client.WaitForStatusOutput waitForStatus(
        @WebParam(name = "WaitForStatusInput", targetNamespace = "")
        com.dpcl2.ws.client.WaitForStatusInput waitForStatusInput
    );

    /**
     * Start a job context in order to submit actions and data. Deprecates .
     */
    @WebMethod(operationName = "StartJob3")
    @RequestWrapper(localName = "StartJob3", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "com.dpcl2.ws.client.StartJob3")
    @ResponseWrapper(localName = "StartJob3Response", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "com.dpcl2.ws.client.StartJob3Response")
    @WebResult(name = "output", targetNamespace = "")
    public com.dpcl2.ws.client.StartJob3Output startJob3(
        @WebParam(name = "StartJob2Input", targetNamespace = "")
        com.dpcl2.ws.client.StartJob2Input startJob2Input
    );

    /**
     * Force-cancel a job.
     */
    @WebMethod(operationName = "CancelJob")
    @RequestWrapper(localName = "CancelJob", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "com.dpcl2.ws.client.CancelJob")
    @ResponseWrapper(localName = "CancelJobResponse", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "com.dpcl2.ws.client.CancelJobResponse")
    @WebResult(name = "output", targetNamespace = "")
    public com.dpcl2.ws.client.CancelJobOutput cancelJob(
        @WebParam(name = "CancelJobInput", targetNamespace = "")
        com.dpcl2.ws.client.CancelJobInput cancelJobInput
    );

    /**
     * Service definition of function DPCL2__StartJob4
     */
    @WebMethod(operationName = "StartJob4")
    @RequestWrapper(localName = "StartJob4", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "com.dpcl2.ws.client.StartJob4")
    @ResponseWrapper(localName = "StartJob3Response", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "com.dpcl2.ws.client.StartJob3Response")
    @WebResult(name = "output", targetNamespace = "")
    public com.dpcl2.ws.client.StartJob3Output startJob4(
        @WebParam(name = "StartJob2Input", targetNamespace = "")
        com.dpcl2.ws.client.StartJob4Input startJob2Input
    );

    /**
     * Finish submitting actions for a job.
     */
    @WebMethod(operationName = "EndJob")
    @RequestWrapper(localName = "EndJob", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "com.dpcl2.ws.client.EndJob")
    @ResponseWrapper(localName = "EndJobResponse", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "com.dpcl2.ws.client.EndJobResponse")
    @WebResult(name = "output", targetNamespace = "")
    public com.dpcl2.ws.client.EndJobOutput endJob(
        @WebParam(name = "EndJobInput", targetNamespace = "")
        com.dpcl2.ws.client.EndJobInput endJobInput
    );

    /**
     * Non-volatile change of the printers ability to accept Jobs. Going from offline to not offline could trigger init job.
     */
    @WebMethod(operationName = "SetJobQueueState")
    @RequestWrapper(localName = "SetJobQueueState", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "com.dpcl2.ws.client.SetJobQueueState")
    @ResponseWrapper(localName = "SetJobQueueStateResponse", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "com.dpcl2.ws.client.SetJobQueueStateResponse")
    @WebResult(name = "output", targetNamespace = "")
    public com.dpcl2.ws.client.SetJobQueueStateOutput setJobQueueState(
        @WebParam(name = "SetJobQueueStateInput", targetNamespace = "")
        com.dpcl2.ws.client.SetJobQueueStateInput setJobQueueStateInput
    );

    /**
     * Retrieve data from an action.
     */
    @WebMethod(operationName = "RetrieveData")
    @RequestWrapper(localName = "RetrieveData", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "com.dpcl2.ws.client.RetrieveData")
    @ResponseWrapper(localName = "RetrieveDataResponse", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "com.dpcl2.ws.client.RetrieveDataResponse")
    @WebResult(name = "output", targetNamespace = "")
    public com.dpcl2.ws.client.RetrieveDataOutput retrieveData(
        @WebParam(name = "RetrieveDataInput", targetNamespace = "")
        com.dpcl2.ws.client.RetrieveDataInput retrieveDataInput
    );

    /**
     * Gracefully resume a job, canceling or continuing as appropriate.
     */
    @WebMethod(operationName = "ResumeJob")
    @RequestWrapper(localName = "ResumeJob", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "com.dpcl2.ws.client.ResumeJob")
    @ResponseWrapper(localName = "ResumeJobResponse", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "com.dpcl2.ws.client.ResumeJobResponse")
    @WebResult(name = "output", targetNamespace = "")
    public com.dpcl2.ws.client.ResumeJobOutput resumeJob(
        @WebParam(name = "ResumeJobInput", targetNamespace = "")
        com.dpcl2.ws.client.ResumeJobInput resumeJobInput
    );

    /**
     * Start a job context in order to submit actions and data. Deprecates .
     */
    @WebMethod(operationName = "StartJob2")
    @RequestWrapper(localName = "StartJob2", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "com.dpcl2.ws.client.StartJob2")
    @ResponseWrapper(localName = "StartJob2Response", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "com.dpcl2.ws.client.StartJob2Response")
    @WebResult(name = "output", targetNamespace = "")
    public com.dpcl2.ws.client.StartJobOutput startJob2(
        @WebParam(name = "StartJob2Input", targetNamespace = "")
        com.dpcl2.ws.client.StartJob2Input startJob2Input
    );

    /**
     * Change the state of the mechanical locks (if any). Unlocking with a key will produce the same effect as calling this method, with the exception that the key could lock the cover open. For that reason, calling unlock with the covers open will retrigger the solenoid activity. Unlocking the system prevents any new actions from becomming Active.
     */
    @WebMethod(operationName = "SetLockState")
    @RequestWrapper(localName = "SetLockState", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "com.dpcl2.ws.client.SetLockState")
    @ResponseWrapper(localName = "SetLockStateResponse", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "com.dpcl2.ws.client.SetLockStateResponse")
    @WebResult(name = "output", targetNamespace = "")
    public com.dpcl2.ws.client.SetLockStateOutput setLockState(
        @WebParam(name = "SetLockStateInput", targetNamespace = "")
        com.dpcl2.ws.client.SetLockStateInput setLockStateInput
    );

    /**
     * Retrieve the current log files, optionally resetting them. When done during an errored state, this also forces the next  to succeed.
     */
    @WebMethod(operationName = "RetrieveLog")
    @RequestWrapper(localName = "RetrieveLog", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "com.dpcl2.ws.client.RetrieveLog")
    @ResponseWrapper(localName = "RetrieveLogResponse", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "com.dpcl2.ws.client.RetrieveLogResponse")
    @WebResult(name = "output", targetNamespace = "")
    public com.dpcl2.ws.client.RetrieveLogOutput retrieveLog(
        @WebParam(name = "RetrieveLogInput", targetNamespace = "")
        com.dpcl2.ws.client.RetrieveLogInput retrieveLogInput
    );
}
