
package com.dpcl2.ws.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.1
 * 2019-03-30T15:10:48.100+08:00
 * Generated source version: 3.3.1
 *
 */
public final class DPCL2PortType_DPCL2Port_Client {

    private static final QName SERVICE_NAME = new QName("urn:dpcl:wsdl:2011-09-02", "DPCL2");

    private DPCL2PortType_DPCL2Port_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = DPCL2.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        DPCL2 ss = new DPCL2(wsdlURL, SERVICE_NAME);
        DPCL2PortType port = ss.getDPCL2Port();

        {
        System.out.println("Invoking submitAction...");
        com.dpcl2.ws.client.SubmitActionInput _submitAction_submitActionInput = null;
        com.dpcl2.ws.client.SubmitActionOutput _submitAction__return = port.submitAction(_submitAction_submitActionInput);
        System.out.println("submitAction.result=" + _submitAction__return);


        }
        {
        System.out.println("Invoking exchangeMessage...");
        com.dpcl2.ws.client.ExchangeMessageInput _exchangeMessage_exchangeMessageInput = null;
        com.dpcl2.ws.client.ExchangeMessageOutput _exchangeMessage__return = port.exchangeMessage(_exchangeMessage_exchangeMessageInput);
        System.out.println("exchangeMessage.result=" + _exchangeMessage__return);


        }
        {
        System.out.println("Invoking startJob...");
        com.dpcl2.ws.client.StartJobInput _startJob_startJobInput = null;
        com.dpcl2.ws.client.StartJobOutput _startJob__return = port.startJob(_startJob_startJobInput);
        System.out.println("startJob.result=" + _startJob__return);


        }
        {
        System.out.println("Invoking setPowerState...");
        com.dpcl2.ws.client.SetPowerStateInput _setPowerState_setPowerStateInput = null;
        com.dpcl2.ws.client.SetPowerStateOutput _setPowerState__return = port.setPowerState(_setPowerState_setPowerStateInput);
        System.out.println("setPowerState.result=" + _setPowerState__return);


        }
        {
        System.out.println("Invoking restartJob...");
        com.dpcl2.ws.client.RestartJobInput _restartJob_restartJobInput = null;
        com.dpcl2.ws.client.RestartJobOutput _restartJob__return = port.restartJob(_restartJob_restartJobInput);
        System.out.println("restartJob.result=" + _restartJob__return);


        }
        {
        System.out.println("Invoking retrieveInfo...");
        com.dpcl2.ws.client.RetrieveInfoInput _retrieveInfo_retrieveInfoInput = null;
        com.dpcl2.ws.client.RetrieveInfoOutput _retrieveInfo__return = port.retrieveInfo(_retrieveInfo_retrieveInfoInput);
        System.out.println("retrieveInfo.result=" + _retrieveInfo__return);


        }
        {
        System.out.println("Invoking discoverPrinter2...");
        com.dpcl2.ws.client.DiscoverPrinter2Input _discoverPrinter2_discoverPrinter2Input = null;
        com.dpcl2.ws.client.DiscoverPrinter2Output _discoverPrinter2__return = port.discoverPrinter2(_discoverPrinter2_discoverPrinter2Input);
        System.out.println("discoverPrinter2.result=" + _discoverPrinter2__return);


        }
        {
        System.out.println("Invoking submitData...");
        com.dpcl2.ws.client.SubmitDataInput _submitData_submitDataInput = null;
        com.dpcl2.ws.client.SubmitDataOutput _submitData__return = port.submitData(_submitData_submitDataInput);
        System.out.println("submitData.result=" + _submitData__return);


        }
        {
        System.out.println("Invoking resumeMessage...");
        com.dpcl2.ws.client.ResumeMessageInput _resumeMessage_resumeMessageInput = null;
        com.dpcl2.ws.client.ResumeMessageOutput _resumeMessage__return = port.resumeMessage(_resumeMessage_resumeMessageInput);
        System.out.println("resumeMessage.result=" + _resumeMessage__return);


        }
        {
        System.out.println("Invoking waitForStatus2...");
        com.dpcl2.ws.client.WaitForStatus2Input _waitForStatus2_waitForStatus2Input = null;
        com.dpcl2.ws.client.WaitForStatus2Output _waitForStatus2__return = port.waitForStatus2(_waitForStatus2_waitForStatus2Input);
        System.out.println("waitForStatus2.result=" + _waitForStatus2__return);


        }
        {
        System.out.println("Invoking discoverPrinter...");
        com.dpcl2.ws.client.DiscoverPrinterInput _discoverPrinter_discoverPrinterInput = null;
        com.dpcl2.ws.client.DiscoverPrinterOutput _discoverPrinter__return = port.discoverPrinter(_discoverPrinter_discoverPrinterInput);
        System.out.println("discoverPrinter.result=" + _discoverPrinter__return);


        }
        {
        System.out.println("Invoking waitForStatus...");
        com.dpcl2.ws.client.WaitForStatusInput _waitForStatus_waitForStatusInput = null;
        com.dpcl2.ws.client.WaitForStatusOutput _waitForStatus__return = port.waitForStatus(_waitForStatus_waitForStatusInput);
        System.out.println("waitForStatus.result=" + _waitForStatus__return);


        }
        {
        System.out.println("Invoking startJob3...");
        com.dpcl2.ws.client.StartJob2Input _startJob3_startJob2Input = null;
        com.dpcl2.ws.client.StartJob3Output _startJob3__return = port.startJob3(_startJob3_startJob2Input);
        System.out.println("startJob3.result=" + _startJob3__return);


        }
        {
        System.out.println("Invoking cancelJob...");
        com.dpcl2.ws.client.CancelJobInput _cancelJob_cancelJobInput = null;
        com.dpcl2.ws.client.CancelJobOutput _cancelJob__return = port.cancelJob(_cancelJob_cancelJobInput);
        System.out.println("cancelJob.result=" + _cancelJob__return);


        }
        {
        System.out.println("Invoking startJob4...");
        com.dpcl2.ws.client.StartJob4Input _startJob4_startJob2Input = null;
        com.dpcl2.ws.client.StartJob3Output _startJob4__return = port.startJob4(_startJob4_startJob2Input);
        System.out.println("startJob4.result=" + _startJob4__return);


        }
        {
        System.out.println("Invoking endJob...");
        com.dpcl2.ws.client.EndJobInput _endJob_endJobInput = null;
        com.dpcl2.ws.client.EndJobOutput _endJob__return = port.endJob(_endJob_endJobInput);
        System.out.println("endJob.result=" + _endJob__return);


        }
        {
        System.out.println("Invoking setJobQueueState...");
        com.dpcl2.ws.client.SetJobQueueStateInput _setJobQueueState_setJobQueueStateInput = null;
        com.dpcl2.ws.client.SetJobQueueStateOutput _setJobQueueState__return = port.setJobQueueState(_setJobQueueState_setJobQueueStateInput);
        System.out.println("setJobQueueState.result=" + _setJobQueueState__return);


        }
        {
        System.out.println("Invoking retrieveData...");
        com.dpcl2.ws.client.RetrieveDataInput _retrieveData_retrieveDataInput = null;
        com.dpcl2.ws.client.RetrieveDataOutput _retrieveData__return = port.retrieveData(_retrieveData_retrieveDataInput);
        System.out.println("retrieveData.result=" + _retrieveData__return);


        }
        {
        System.out.println("Invoking resumeJob...");
        com.dpcl2.ws.client.ResumeJobInput _resumeJob_resumeJobInput = null;
        com.dpcl2.ws.client.ResumeJobOutput _resumeJob__return = port.resumeJob(_resumeJob_resumeJobInput);
        System.out.println("resumeJob.result=" + _resumeJob__return);


        }
        {
        System.out.println("Invoking startJob2...");
        com.dpcl2.ws.client.StartJob2Input _startJob2_startJob2Input = null;
        com.dpcl2.ws.client.StartJobOutput _startJob2__return = port.startJob2(_startJob2_startJob2Input);
        System.out.println("startJob2.result=" + _startJob2__return);


        }
        {
        System.out.println("Invoking setLockState...");
        com.dpcl2.ws.client.SetLockStateInput _setLockState_setLockStateInput = null;
        com.dpcl2.ws.client.SetLockStateOutput _setLockState__return = port.setLockState(_setLockState_setLockStateInput);
        System.out.println("setLockState.result=" + _setLockState__return);


        }
        {
        System.out.println("Invoking retrieveLog...");
        com.dpcl2.ws.client.RetrieveLogInput _retrieveLog_retrieveLogInput = null;
        com.dpcl2.ws.client.RetrieveLogOutput _retrieveLog__return = port.retrieveLog(_retrieveLog_retrieveLogInput);
        System.out.println("retrieveLog.result=" + _retrieveLog__return);


        }

        System.exit(0);
    }

}
