
package dpcl.wsdl._2011_09_02;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.1
 * 2019-03-30T12:49:44.034+08:00
 * Generated source version: 3.3.1
 *
 */
public final class DPCL2PortType_DPCL2SecurePort_Client {

    private static final QName SERVICE_NAME = new QName("urn:dpcl:wsdl:2011-09-02", "DPCL2");

    private DPCL2PortType_DPCL2SecurePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = DPCL2.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        DPCL2 ss = new DPCL2(wsdlURL, SERVICE_NAME);
        DPCL2PortType port = ss.getDPCL2SecurePort();

        {
        System.out.println("Invoking submitAction...");
        dpcl.wsdl._2010_01_19.SubmitActionInput _submitAction_submitActionInput = null;
        dpcl.wsdl._2010_01_19.SubmitActionOutput _submitAction__return = port.submitAction(_submitAction_submitActionInput);
        System.out.println("submitAction.result=" + _submitAction__return);


        }
        {
        System.out.println("Invoking exchangeMessage...");
        dpcl.wsdl._2011_09_02.ExchangeMessageInput _exchangeMessage_exchangeMessageInput = null;
        dpcl.wsdl._2011_09_02.ExchangeMessageOutput _exchangeMessage__return = port.exchangeMessage(_exchangeMessage_exchangeMessageInput);
        System.out.println("exchangeMessage.result=" + _exchangeMessage__return);


        }
        {
        System.out.println("Invoking startJob...");
        dpcl.wsdl._2010_01_19.StartJobInput _startJob_startJobInput = null;
        dpcl.wsdl._2010_01_19.StartJobOutput _startJob__return = port.startJob(_startJob_startJobInput);
        System.out.println("startJob.result=" + _startJob__return);


        }
        {
        System.out.println("Invoking setPowerState...");
        dpcl.wsdl._2011_09_02.SetPowerStateInput _setPowerState_setPowerStateInput = null;
        dpcl.wsdl._2011_09_02.SetPowerStateOutput _setPowerState__return = port.setPowerState(_setPowerState_setPowerStateInput);
        System.out.println("setPowerState.result=" + _setPowerState__return);


        }
        {
        System.out.println("Invoking restartJob...");
        dpcl.wsdl._2010_01_19.RestartJobInput _restartJob_restartJobInput = null;
        dpcl.wsdl._2010_01_19.RestartJobOutput _restartJob__return = port.restartJob(_restartJob_restartJobInput);
        System.out.println("restartJob.result=" + _restartJob__return);


        }
        {
        System.out.println("Invoking retrieveInfo...");
        dpcl.wsdl._2011_09_02.RetrieveInfoInput _retrieveInfo_retrieveInfoInput = null;
        dpcl.wsdl._2011_09_02.RetrieveInfoOutput _retrieveInfo__return = port.retrieveInfo(_retrieveInfo_retrieveInfoInput);
        System.out.println("retrieveInfo.result=" + _retrieveInfo__return);


        }
        {
        System.out.println("Invoking discoverPrinter2...");
        dpcl.wsdl._2011_09_02.DiscoverPrinter2Input _discoverPrinter2_discoverPrinter2Input = null;
        dpcl.wsdl._2011_09_02.DiscoverPrinter2Output _discoverPrinter2__return = port.discoverPrinter2(_discoverPrinter2_discoverPrinter2Input);
        System.out.println("discoverPrinter2.result=" + _discoverPrinter2__return);


        }
        {
        System.out.println("Invoking submitData...");
        dpcl.wsdl._2010_01_19.SubmitDataInput _submitData_submitDataInput = null;
        dpcl.wsdl._2010_01_19.SubmitDataOutput _submitData__return = port.submitData(_submitData_submitDataInput);
        System.out.println("submitData.result=" + _submitData__return);


        }
        {
        System.out.println("Invoking resumeMessage...");
        dpcl.wsdl._2011_09_02.ResumeMessageInput _resumeMessage_resumeMessageInput = null;
        dpcl.wsdl._2011_09_02.ResumeMessageOutput _resumeMessage__return = port.resumeMessage(_resumeMessage_resumeMessageInput);
        System.out.println("resumeMessage.result=" + _resumeMessage__return);


        }
        {
        System.out.println("Invoking waitForStatus2...");
        dpcl.wsdl._2011_09_02.WaitForStatus2Input _waitForStatus2_waitForStatus2Input = null;
        dpcl.wsdl._2011_09_02.WaitForStatus2Output _waitForStatus2__return = port.waitForStatus2(_waitForStatus2_waitForStatus2Input);
        System.out.println("waitForStatus2.result=" + _waitForStatus2__return);


        }
        {
        System.out.println("Invoking discoverPrinter...");
        dpcl.wsdl._2010_01_19.DiscoverPrinterInput _discoverPrinter_discoverPrinterInput = null;
        dpcl.wsdl._2010_01_19.DiscoverPrinterOutput _discoverPrinter__return = port.discoverPrinter(_discoverPrinter_discoverPrinterInput);
        System.out.println("discoverPrinter.result=" + _discoverPrinter__return);


        }
        {
        System.out.println("Invoking waitForStatus...");
        dpcl.wsdl._2010_01_19.WaitForStatusInput _waitForStatus_waitForStatusInput = null;
        dpcl.wsdl._2010_01_19.WaitForStatusOutput _waitForStatus__return = port.waitForStatus(_waitForStatus_waitForStatusInput);
        System.out.println("waitForStatus.result=" + _waitForStatus__return);


        }
        {
        System.out.println("Invoking startJob3...");
        dpcl.wsdl._2011_09_02.StartJob2Input _startJob3_startJob2Input = null;
        dpcl.wsdl._2011_09_02.StartJob3Output _startJob3__return = port.startJob3(_startJob3_startJob2Input);
        System.out.println("startJob3.result=" + _startJob3__return);


        }
        {
        System.out.println("Invoking cancelJob...");
        dpcl.wsdl._2010_01_19.CancelJobInput _cancelJob_cancelJobInput = null;
        dpcl.wsdl._2010_01_19.CancelJobOutput _cancelJob__return = port.cancelJob(_cancelJob_cancelJobInput);
        System.out.println("cancelJob.result=" + _cancelJob__return);


        }
        {
        System.out.println("Invoking startJob4...");
        dpcl.wsdl._2011_09_02.StartJob4Input _startJob4_startJob2Input = null;
        dpcl.wsdl._2011_09_02.StartJob3Output _startJob4__return = port.startJob4(_startJob4_startJob2Input);
        System.out.println("startJob4.result=" + _startJob4__return);


        }
        {
        System.out.println("Invoking endJob...");
        dpcl.wsdl._2010_01_19.EndJobInput _endJob_endJobInput = null;
        dpcl.wsdl._2010_01_19.EndJobOutput _endJob__return = port.endJob(_endJob_endJobInput);
        System.out.println("endJob.result=" + _endJob__return);


        }
        {
        System.out.println("Invoking setJobQueueState...");
        dpcl.wsdl._2011_09_02.SetJobQueueStateInput _setJobQueueState_setJobQueueStateInput = null;
        dpcl.wsdl._2011_09_02.SetJobQueueStateOutput _setJobQueueState__return = port.setJobQueueState(_setJobQueueState_setJobQueueStateInput);
        System.out.println("setJobQueueState.result=" + _setJobQueueState__return);


        }
        {
        System.out.println("Invoking retrieveData...");
        dpcl.wsdl._2010_01_19.RetrieveDataInput _retrieveData_retrieveDataInput = null;
        dpcl.wsdl._2010_01_19.RetrieveDataOutput _retrieveData__return = port.retrieveData(_retrieveData_retrieveDataInput);
        System.out.println("retrieveData.result=" + _retrieveData__return);


        }
        {
        System.out.println("Invoking resumeJob...");
        dpcl.wsdl._2010_01_19.ResumeJobInput _resumeJob_resumeJobInput = null;
        dpcl.wsdl._2010_01_19.ResumeJobOutput _resumeJob__return = port.resumeJob(_resumeJob_resumeJobInput);
        System.out.println("resumeJob.result=" + _resumeJob__return);


        }
        {
        System.out.println("Invoking startJob2...");
        dpcl.wsdl._2011_09_02.StartJob2Input _startJob2_startJob2Input = null;
        dpcl.wsdl._2010_01_19.StartJobOutput _startJob2__return = port.startJob2(_startJob2_startJob2Input);
        System.out.println("startJob2.result=" + _startJob2__return);


        }
        {
        System.out.println("Invoking setLockState...");
        dpcl.wsdl._2011_09_02.SetLockStateInput _setLockState_setLockStateInput = null;
        dpcl.wsdl._2011_09_02.SetLockStateOutput _setLockState__return = port.setLockState(_setLockState_setLockStateInput);
        System.out.println("setLockState.result=" + _setLockState__return);


        }
        {
        System.out.println("Invoking retrieveLog...");
        dpcl.wsdl._2011_09_02.RetrieveLogInput _retrieveLog_retrieveLogInput = null;
        dpcl.wsdl._2011_09_02.RetrieveLogOutput _retrieveLog__return = port.retrieveLog(_retrieveLog_retrieveLogInput);
        System.out.println("retrieveLog.result=" + _retrieveLog__return);


        }

        System.exit(0);
    }

}
