package dpcl.wsdl._2011_09_02;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.1
 * 2019-03-30T12:49:44.095+08:00
 * Generated source version: 3.3.1
 *
 */
@WebService(targetNamespace = "urn:dpcl:wsdl:2011-09-02", name = "DPCL2PortType")
@XmlSeeAlso({dpcl.sensors._2010_01_19.ObjectFactory.class, org.w3._2004._08.xop.include.ObjectFactory.class, dpcl.emboss._2011_06_03.ObjectFactory.class, dpcl.settings._2010_01_19.ObjectFactory.class, dpcl.update._2011_10_19.ObjectFactory.class, dpcl.magstripe._2010_01_19.ObjectFactory.class, ObjectFactory.class, dpcl.wheel._2011_06_03.ObjectFactory.class, dpcl.wsdl._2010_01_19.ObjectFactory.class, dpcl.nal._2012_05_30.ObjectFactory.class, org.w3._2005._05.xmlmime.ObjectFactory.class})
public interface DPCL2PortType {

    /**
     * Add actions to a job.
     */
    @WebMethod(operationName = "SubmitAction")
    @RequestWrapper(localName = "SubmitAction", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "dpcl.wsdl._2011_09_02.SubmitAction")
    @ResponseWrapper(localName = "SubmitActionResponse", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "dpcl.wsdl._2011_09_02.SubmitActionResponse")
    @WebResult(name = "output", targetNamespace = "")
    public dpcl.wsdl._2010_01_19.SubmitActionOutput submitAction(
        @WebParam(name = "SubmitActionInput", targetNamespace = "")
        dpcl.wsdl._2010_01_19.SubmitActionInput submitActionInput
    );

    /**
     * Exchange a message with a tunnel.
     */
    @WebMethod(operationName = "ExchangeMessage")
    @RequestWrapper(localName = "ExchangeMessage", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "dpcl.wsdl._2011_09_02.ExchangeMessage")
    @ResponseWrapper(localName = "ExchangeMessageResponse", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "dpcl.wsdl._2011_09_02.ExchangeMessageResponse")
    @WebResult(name = "output", targetNamespace = "")
    public dpcl.wsdl._2011_09_02.ExchangeMessageOutput exchangeMessage(
        @WebParam(name = "ExchangeMessageInput", targetNamespace = "")
        dpcl.wsdl._2011_09_02.ExchangeMessageInput exchangeMessageInput
    );

    @WebMethod(operationName = "StartJob")
    @RequestWrapper(localName = "StartJob", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "dpcl.wsdl._2011_09_02.StartJob")
    @ResponseWrapper(localName = "StartJobResponse", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "dpcl.wsdl._2011_09_02.StartJobResponse")
    @WebResult(name = "output", targetNamespace = "")
    public dpcl.wsdl._2010_01_19.StartJobOutput startJob(
        @WebParam(name = "StartJobInput", targetNamespace = "")
        dpcl.wsdl._2010_01_19.StartJobInput startJobInput
    );

    /**
     * Change the power state of the printer.
     */
    @WebMethod(operationName = "SetPowerState")
    @RequestWrapper(localName = "SetPowerState", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "dpcl.wsdl._2011_09_02.SetPowerState")
    @ResponseWrapper(localName = "SetPowerStateResponse", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "dpcl.wsdl._2011_09_02.SetPowerStateResponse")
    @WebResult(name = "output", targetNamespace = "")
    public dpcl.wsdl._2011_09_02.SetPowerStateOutput setPowerState(
        @WebParam(name = "SetPowerStateInput", targetNamespace = "")
        dpcl.wsdl._2011_09_02.SetPowerStateInput setPowerStateInput
    );

    /**
     * Attempt to force-complete a job.
     */
    @WebMethod(operationName = "RestartJob")
    @RequestWrapper(localName = "RestartJob", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "dpcl.wsdl._2011_09_02.RestartJob")
    @ResponseWrapper(localName = "RestartJobResponse", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "dpcl.wsdl._2011_09_02.RestartJobResponse")
    @WebResult(name = "output", targetNamespace = "")
    public dpcl.wsdl._2010_01_19.RestartJobOutput restartJob(
        @WebParam(name = "RestartJobInput", targetNamespace = "")
        dpcl.wsdl._2010_01_19.RestartJobInput restartJobInput
    );

    /**
     * Service definition of function DPCL2__RetrieveInfo
     */
    @WebMethod(operationName = "RetrieveInfo")
    @RequestWrapper(localName = "RetrieveInfo", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "dpcl.wsdl._2011_09_02.RetrieveInfo")
    @ResponseWrapper(localName = "RetrieveInfoResponse", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "dpcl.wsdl._2011_09_02.RetrieveInfoResponse")
    @WebResult(name = "output", targetNamespace = "")
    public dpcl.wsdl._2011_09_02.RetrieveInfoOutput retrieveInfo(
        @WebParam(name = "RetrieveInfoInput", targetNamespace = "")
        dpcl.wsdl._2011_09_02.RetrieveInfoInput retrieveInfoInput
    );

    /**
     * Discover static information about the printer. Deprecates .
     */
    @WebMethod(operationName = "DiscoverPrinter2")
    @RequestWrapper(localName = "DiscoverPrinter2", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "dpcl.wsdl._2011_09_02.DiscoverPrinter2")
    @ResponseWrapper(localName = "DiscoverPrinter2Response", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "dpcl.wsdl._2011_09_02.DiscoverPrinter2Response")
    @WebResult(name = "output", targetNamespace = "")
    public dpcl.wsdl._2011_09_02.DiscoverPrinter2Output discoverPrinter2(
        @WebParam(name = "DiscoverPrinter2Input", targetNamespace = "")
        dpcl.wsdl._2011_09_02.DiscoverPrinter2Input discoverPrinter2Input
    );

    /**
     * Submit data to an action.
     */
    @WebMethod(operationName = "SubmitData")
    @RequestWrapper(localName = "SubmitData", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "dpcl.wsdl._2011_09_02.SubmitData")
    @ResponseWrapper(localName = "SubmitDataResponse", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "dpcl.wsdl._2011_09_02.SubmitDataResponse")
    @WebResult(name = "output", targetNamespace = "")
    public dpcl.wsdl._2010_01_19.SubmitDataOutput submitData(
        @WebParam(name = "SubmitDataInput", targetNamespace = "")
        dpcl.wsdl._2010_01_19.SubmitDataInput submitDataInput
    );

    /**
     * Reusume a previously Exchanged message that timed out.
     */
    @WebMethod(operationName = "ResumeMessage")
    @RequestWrapper(localName = "ResumeMessage", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "dpcl.wsdl._2011_09_02.ResumeMessage")
    @ResponseWrapper(localName = "ResumeMessageResponse", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "dpcl.wsdl._2011_09_02.ResumeMessageResponse")
    @WebResult(name = "output", targetNamespace = "")
    public dpcl.wsdl._2011_09_02.ResumeMessageOutput resumeMessage(
        @WebParam(name = "ResumeMessageInput", targetNamespace = "")
        dpcl.wsdl._2011_09_02.ResumeMessageInput resumeMessageInput
    );

    @WebMethod(operationName = "WaitForStatus2")
    @RequestWrapper(localName = "WaitForStatus2", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "dpcl.wsdl._2011_09_02.WaitForStatus2")
    @ResponseWrapper(localName = "WaitForStatus2Response", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "dpcl.wsdl._2011_09_02.WaitForStatus2Response")
    @WebResult(name = "output", targetNamespace = "")
    public dpcl.wsdl._2011_09_02.WaitForStatus2Output waitForStatus2(
        @WebParam(name = "WaitForStatus2Input", targetNamespace = "")
        dpcl.wsdl._2011_09_02.WaitForStatus2Input waitForStatus2Input
    );

    /**
     * Discover static information about the printer.
     */
    @WebMethod(operationName = "DiscoverPrinter")
    @RequestWrapper(localName = "DiscoverPrinter", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "dpcl.wsdl._2011_09_02.DiscoverPrinter")
    @ResponseWrapper(localName = "DiscoverPrinterResponse", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "dpcl.wsdl._2011_09_02.DiscoverPrinterResponse")
    @WebResult(name = "output", targetNamespace = "")
    public dpcl.wsdl._2010_01_19.DiscoverPrinterOutput discoverPrinter(
        @WebParam(name = "DiscoverPrinterInput", targetNamespace = "")
        dpcl.wsdl._2010_01_19.DiscoverPrinterInput discoverPrinterInput
    );

    /**
     * Get status on printer, supplies and jobs with adjustable triggers.
     */
    @WebMethod(operationName = "WaitForStatus")
    @RequestWrapper(localName = "WaitForStatus", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "dpcl.wsdl._2011_09_02.WaitForStatus")
    @ResponseWrapper(localName = "WaitForStatusResponse", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "dpcl.wsdl._2011_09_02.WaitForStatusResponse")
    @WebResult(name = "output", targetNamespace = "")
    public dpcl.wsdl._2010_01_19.WaitForStatusOutput waitForStatus(
        @WebParam(name = "WaitForStatusInput", targetNamespace = "")
        dpcl.wsdl._2010_01_19.WaitForStatusInput waitForStatusInput
    );

    /**
     * Start a job context in order to submit actions and data. Deprecates .
     */
    @WebMethod(operationName = "StartJob3")
    @RequestWrapper(localName = "StartJob3", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "dpcl.wsdl._2011_09_02.StartJob3")
    @ResponseWrapper(localName = "StartJob3Response", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "dpcl.wsdl._2011_09_02.StartJob3Response")
    @WebResult(name = "output", targetNamespace = "")
    public dpcl.wsdl._2011_09_02.StartJob3Output startJob3(
        @WebParam(name = "StartJob2Input", targetNamespace = "")
        dpcl.wsdl._2011_09_02.StartJob2Input startJob2Input
    );

    /**
     * Force-cancel a job.
     */
    @WebMethod(operationName = "CancelJob")
    @RequestWrapper(localName = "CancelJob", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "dpcl.wsdl._2011_09_02.CancelJob")
    @ResponseWrapper(localName = "CancelJobResponse", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "dpcl.wsdl._2011_09_02.CancelJobResponse")
    @WebResult(name = "output", targetNamespace = "")
    public dpcl.wsdl._2010_01_19.CancelJobOutput cancelJob(
        @WebParam(name = "CancelJobInput", targetNamespace = "")
        dpcl.wsdl._2010_01_19.CancelJobInput cancelJobInput
    );

    /**
     * Service definition of function DPCL2__StartJob4
     */
    @WebMethod(operationName = "StartJob4")
    @RequestWrapper(localName = "StartJob4", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "dpcl.wsdl._2011_09_02.StartJob4")
    @ResponseWrapper(localName = "StartJob3Response", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "dpcl.wsdl._2011_09_02.StartJob3Response")
    @WebResult(name = "output", targetNamespace = "")
    public dpcl.wsdl._2011_09_02.StartJob3Output startJob4(
        @WebParam(name = "StartJob2Input", targetNamespace = "")
        dpcl.wsdl._2011_09_02.StartJob4Input startJob2Input
    );

    /**
     * Finish submitting actions for a job.
     */
    @WebMethod(operationName = "EndJob")
    @RequestWrapper(localName = "EndJob", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "dpcl.wsdl._2011_09_02.EndJob")
    @ResponseWrapper(localName = "EndJobResponse", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "dpcl.wsdl._2011_09_02.EndJobResponse")
    @WebResult(name = "output", targetNamespace = "")
    public dpcl.wsdl._2010_01_19.EndJobOutput endJob(
        @WebParam(name = "EndJobInput", targetNamespace = "")
        dpcl.wsdl._2010_01_19.EndJobInput endJobInput
    );

    /**
     * Non-volatile change of the printers ability to accept Jobs. Going from offline to not offline could trigger init job.
     */
    @WebMethod(operationName = "SetJobQueueState")
    @RequestWrapper(localName = "SetJobQueueState", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "dpcl.wsdl._2011_09_02.SetJobQueueState")
    @ResponseWrapper(localName = "SetJobQueueStateResponse", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "dpcl.wsdl._2011_09_02.SetJobQueueStateResponse")
    @WebResult(name = "output", targetNamespace = "")
    public dpcl.wsdl._2011_09_02.SetJobQueueStateOutput setJobQueueState(
        @WebParam(name = "SetJobQueueStateInput", targetNamespace = "")
        dpcl.wsdl._2011_09_02.SetJobQueueStateInput setJobQueueStateInput
    );

    /**
     * Retrieve data from an action.
     */
    @WebMethod(operationName = "RetrieveData")
    @RequestWrapper(localName = "RetrieveData", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "dpcl.wsdl._2011_09_02.RetrieveData")
    @ResponseWrapper(localName = "RetrieveDataResponse", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "dpcl.wsdl._2011_09_02.RetrieveDataResponse")
    @WebResult(name = "output", targetNamespace = "")
    public dpcl.wsdl._2010_01_19.RetrieveDataOutput retrieveData(
        @WebParam(name = "RetrieveDataInput", targetNamespace = "")
        dpcl.wsdl._2010_01_19.RetrieveDataInput retrieveDataInput
    );

    /**
     * Gracefully resume a job, canceling or continuing as appropriate.
     */
    @WebMethod(operationName = "ResumeJob")
    @RequestWrapper(localName = "ResumeJob", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "dpcl.wsdl._2011_09_02.ResumeJob")
    @ResponseWrapper(localName = "ResumeJobResponse", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "dpcl.wsdl._2011_09_02.ResumeJobResponse")
    @WebResult(name = "output", targetNamespace = "")
    public dpcl.wsdl._2010_01_19.ResumeJobOutput resumeJob(
        @WebParam(name = "ResumeJobInput", targetNamespace = "")
        dpcl.wsdl._2010_01_19.ResumeJobInput resumeJobInput
    );

    /**
     * Start a job context in order to submit actions and data. Deprecates .
     */
    @WebMethod(operationName = "StartJob2")
    @RequestWrapper(localName = "StartJob2", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "dpcl.wsdl._2011_09_02.StartJob2")
    @ResponseWrapper(localName = "StartJob2Response", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "dpcl.wsdl._2011_09_02.StartJob2Response")
    @WebResult(name = "output", targetNamespace = "")
    public dpcl.wsdl._2010_01_19.StartJobOutput startJob2(
        @WebParam(name = "StartJob2Input", targetNamespace = "")
        dpcl.wsdl._2011_09_02.StartJob2Input startJob2Input
    );

    /**
     * Change the state of the mechanical locks (if any). Unlocking with a key will produce the same effect as calling this method, with the exception that the key could lock the cover open. For that reason, calling unlock with the covers open will retrigger the solenoid activity. Unlocking the system prevents any new actions from becomming Active.
     */
    @WebMethod(operationName = "SetLockState")
    @RequestWrapper(localName = "SetLockState", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "dpcl.wsdl._2011_09_02.SetLockState")
    @ResponseWrapper(localName = "SetLockStateResponse", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "dpcl.wsdl._2011_09_02.SetLockStateResponse")
    @WebResult(name = "output", targetNamespace = "")
    public dpcl.wsdl._2011_09_02.SetLockStateOutput setLockState(
        @WebParam(name = "SetLockStateInput", targetNamespace = "")
        dpcl.wsdl._2011_09_02.SetLockStateInput setLockStateInput
    );

    /**
     * Retrieve the current log files, optionally resetting them. When done during an errored state, this also forces the next  to succeed.
     */
    @WebMethod(operationName = "RetrieveLog")
    @RequestWrapper(localName = "RetrieveLog", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "dpcl.wsdl._2011_09_02.RetrieveLog")
    @ResponseWrapper(localName = "RetrieveLogResponse", targetNamespace = "urn:dpcl:wsdl:2011-09-02", className = "dpcl.wsdl._2011_09_02.RetrieveLogResponse")
    @WebResult(name = "output", targetNamespace = "")
    public dpcl.wsdl._2011_09_02.RetrieveLogOutput retrieveLog(
        @WebParam(name = "RetrieveLogInput", targetNamespace = "")
        dpcl.wsdl._2011_09_02.RetrieveLogInput retrieveLogInput
    );
}
